reading a JSON file and loading its data in a LIST

In [ ]:
import json

#NOTE : before running this snippet, load the Sarcasm_Headlines_Dataset_v2.json dataset in PATH : /content/sarcasmDetection/Sarcasm_Headlines_Dataset_v2.json

#f = open('/content/sarcasmDetection/Sarcasm_Headlines_Dataset_v2.json','r')
#for line in f:
  #print(line)

########## READING A JSON FILE & LOADING ITS CONTENTS IN THEIR RESPECTIVE LISTS ##########
with open('/content/sarcasmDetection/Sarcasm_Headlines_Dataset_v2.json','r') as f:
  datastore = json.load(f)
   

print(datastore)

isSarcastic = []
headline = []
articleLink = []
for item in datastore:
  #print(item)
  #print(item['headline'])
  isSarcastic.append(item['is_sarcastic'])
  #print(isSarcastic)
  headline.append(item['headline'])
  articleLink.append(item['article_link'])
print(headline)

#########################################################################################

[{'is_sarcastic': 1, 'headline': 'thirtysomething scientists unveil doomsday clock of hair loss', 'article_link': 'https://www.theonion.com/thirtysomething-scientists-unveil-doomsday-clock-of-hai-1819586205'}, {'is_sarcastic': 0, 'headline': 'dem rep. totally nails why congress is falling short on gender, racial equality', 'article_link': 'https://www.huffingtonpost.com/entry/donna-edwards-inequality_us_57455f7fe4b055bb1170b207'}, {'is_sarcastic': 0, 'headline': 'eat your veggies: 9 deliciously different recipes', 'article_link': 'https://www.huffingtonpost.com/entry/eat-your-veggies-9-delici_b_8899742.html'}, {'is_sarcastic': 1, 'headline': 'inclement weather prevents liar from getting to work', 'article_link': 'https://local.theonion.com/inclement-weather-prevents-liar-from-getting-to-work-1819576031'}, {'is_sarcastic': 1, 'headline': "mother comes pretty close to using word 'streaming' correctly", 'article_link': 'https://www.theonion.com/mother-comes-pretty-close-to-using-word-stre

In [ ]:
import numpy as np

training_size = 3700

training_headlines =  headline[0:training_size]
training_labels = np.array(isSarcastic[0:training_size])
testing_headlines = headline[training_size:]
testing_labels = np.array(isSarcastic[training_size:])

#print(training_headlines)
#print(testing_headlines)

In [ ]:
## IMPORT LIBRARIES ##

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [ ]:
## TOKENIZE THE STATEMENTS ##
numWords = 10000
oovToken = "<oov>"

tokenizer = Tokenizer(num_words=numWords, oov_token=oovToken)
tokenizer.fit_on_texts(training_headlines)
#tokenizer.word_index
training_sequences = tokenizer.texts_to_sequences(training_headlines)
testing_sequences = tokenizer.texts_to_sequences(testing_headlines)

print(training_sequences)

[[4147, 223, 1815, 4148, 2579, 3, 505, 661], [4149, 1396, 506, 1111, 42, 329, 12, 1816, 456, 8, 1817, 1818, 2580], [1819, 32, 4150, 197, 4151, 911, 1820], [4152, 1821, 4153, 4154, 17, 117, 2, 103], [259, 414, 284, 753, 2, 662, 507, 4155, 4156], [104, 65, 4157], [74, 224, 2, 4158, 32, 1397, 10, 508, 912], [1398, 4159, 583, 1822, 2581, 1112, 29, 285, 29, 754, 3, 755, 2582, 4160], [913, 260, 117, 172, 584, 2, 457, 5, 4161, 663, 367, 914], [1113, 3, 128, 97, 22, 2583], [22, 4162, 12, 1823, 7, 458, 5, 4163, 9, 72, 585, 40, 13, 24], [4164, 4165, 915, 60, 586, 243, 12, 756, 509, 4166], [34, 2, 97, 4167, 4168, 4169, 6, 1114], [330, 1115, 757, 190, 79, 73, 2, 1824, 6, 4170, 4171, 4172, 3, 664, 3, 4173], [758, 4174, 11, 2584, 24, 916, 4175, 8, 4176], [1116, 415, 4177, 4178, 4179, 80, 17, 15, 2585, 1825, 1399], [49, 416, 1400, 2586, 9, 4180, 917, 3, 4181, 2587], [49, 14, 225, 118, 3, 31, 1826, 18, 4182], [1117, 57, 368, 10, 4183, 226], [1827, 1828, 1829, 107, 52, 2, 2588, 21, 2, 759, 32, 510, 261

In [ ]:
## PADDING ##
maxLen = 120
paddingStyle = 'post'

training_seq_padded = pad_sequences(training_sequences, maxlen=maxLen, padding=paddingStyle)
testing_seq_padded = pad_sequences(testing_sequences, maxlen=maxLen, padding=paddingStyle)

print(training_seq_padded)

[[4147  223 1815 ...    0    0    0]
 [4149 1396  506 ...    0    0    0]
 [1819   32 4150 ...    0    0    0]
 ...
 [ 303    1   51 ...    0    0    0]
 [  40    1  724 ...    0    0    0]
 [ 124 2560  224 ...    0    0    0]]


In [ ]:
reverse_word_index = dict([(value, key) for (key, value) in tokenizer.word_index.items()])

def decode_review(text):
    return ' '.join([reverse_word_index.get(i, '?') for i in text])

print(decode_review(training_seq_padded[100]))
print(training_headlines[100])

report 70 of trump endorsements made after staring at bedroom ceiling for 4 hours ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ? ?
report: 70% of trump endorsements made after staring at bedroom ceiling for 4 hours


In [ ]:
import tensorflow as tf

embedding_dim = 16

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(numWords, embedding_dim, input_length=maxLen),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(6, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 120, 16)           160000    
_________________________________________________________________
flatten_2 (Flatten)          (None, 1920)              0         
_________________________________________________________________
dense_4 (Dense)              (None, 6)                 11526     
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 7         
Total params: 171,533
Trainable params: 171,533
Non-trainable params: 0
_________________________________________________________________


In [ ]:
num_epochs = 10
model.fit(training_seq_padded, training_labels, epochs=num_epochs, validation_data=(testing_seq_padded, testing_labels))

Epoch 1/10
116/116 [==============================] - 0s 4ms/step - loss: 0.6874 - accuracy: 0.5605 - val_loss: 0.6676 - val_accuracy: 0.6605
Epoch 2/10
116/116 [==============================] - 0s 3ms/step - loss: 0.5399 - accuracy: 0.8381 - val_loss: 0.4668 - val_accuracy: 0.7828
Epoch 3/10
116/116 [==============================] - 0s 3ms/step - loss: 0.2355 - accuracy: 0.9427 - val_loss: 0.4113 - val_accuracy: 0.8033
Epoch 4/10
116/116 [==============================] - 0s 3ms/step - loss: 0.0829 - accuracy: 0.9886 - val_loss: 0.4310 - val_accuracy: 0.8063
Epoch 5/10
116/116 [==============================] - 0s 3ms/step - loss: 0.0319 - accuracy: 0.9992 - val_loss: 0.4469 - val_accuracy: 0.8043
Epoch 6/10
116/116 [==============================] - 0s 3ms/step - loss: 0.0151 - accuracy: 0.9997 - val_loss: 0.4713 - val_accuracy: 0.8033
Epoch 7/10
116/116 [==============================] - 0s 3ms/step - loss: 0.0086 - accuracy: 1.0000 - val_loss: 0.4759 - val_accuracy: 0.8033
Epoch 

In [ ]:
e = model.layers[0]
weights = e.get_weights()[0]
print(weights.shape) # shape: (vocab_size, embedding_dim)

(10000, 16)


In [ ]:
import io

print(reverse_word_index)

out_v = io.open('vecs.tsv', 'w', encoding='utf-8')
out_m = io.open('meta.tsv', 'w', encoding='utf-8')
for word_num in range(1, numWords):
  word = reverse_word_index[word_num]
  embeddings = weights[word_num]
  out_m.write(word + "\n")
  out_v.write('\t'.join([str(x) for x in embeddings]) + "\n")
out_v.close()
out_m.close()

{1: '<oov>', 2: 'to', 3: 'of', 4: 'the', 5: 'in', 6: 'for', 7: 'a', 8: 'on', 9: 'and', 10: 'with', 11: 'new', 12: 'is', 13: 'at', 14: 'man', 15: 'trump', 16: 'about', 17: 'from', 18: 'by', 19: 'out', 20: 'after', 21: 'you', 22: 'this', 23: 'be', 24: 'that', 25: 'how', 26: 'up', 27: 'not', 28: 'it', 29: 'as', 30: 'he', 31: 'his', 32: 'your', 33: 'into', 34: 'what', 35: 'report', 36: 'are', 37: 'just', 38: 'who', 39: 'has', 40: 'one', 41: 'have', 42: 'why', 43: 'all', 44: 'more', 45: 'will', 46: 'can', 47: 'first', 48: 'day', 49: 'area', 50: 'year', 51: 'says', 52: 'like', 53: 'life', 54: 'donald', 55: 's', 56: 'house', 57: 'no', 58: 'u', 59: 'woman', 60: 'her', 61: 'over', 62: 'get', 63: 'old', 64: 'time', 65: 'white', 66: 'off', 67: 'now', 68: "'", 69: 'people', 70: 'women', 71: 'obama', 72: 'an', 73: 'was', 74: '5', 75: 'so', 76: 'back', 77: 'when', 78: 'if', 79: 'clinton', 80: 'down', 81: 'still', 82: 'than', 83: 'world', 84: 'americans', 85: 'their', 86: "trump's", 87: 'we', 88: 'i'

In [ ]:
try:
  from google.colab import files
except ImportError:
  pass
else:
  files.download('vecs.tsv')
  files.download('meta.tsv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>